services:
  db:
    container_name: ${SITE_NAME:cove}
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data_${SITE_NAME:cove}:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=${SITE_NAME:cove}

volumes:
  postgres_data_cove:
